# Generated by Django 4.2.6 on 2023-11-01 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_userprofileinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
